# Site settings
title: Notion.farm
email: notionpod@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Start with a rant, end with a new idea. Hosted by Chris Radcliff and Ben Etherington
baseurl: "" # the subpath of your site, e.g. /blog
timezone: America/Los_Angeles
url: "notion.farm" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: notionpod
permalink: :title.html
# github_username:  jekyll




# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
