# Site settings
title: Notion.farm
email: notionpod@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Start with a rant, end with a new idea. Hosted by Chris Radcliff and Ben Etherington.
baseurl: "" # the subpath of your site, e.g. /blog
timezone: America/Los_Angeles
url: http://notion.farm # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: notion_farm
permalink: :title.html

# Hydejack theme settings
image: /images/grass-blurred.jpg
color: '#006600'
google_analytics: ''
paginate: 5
paginate_path: '/page-:num/'
show_social:
  twitter: notion-farm
  email: mailto:notion.pod@gmail.com
  rss: http://notion.farm/podcast.rss
related_posts_disabled: false

# Build settings
markdown: kramdown
theme: jekyll-theme-hydejack
gems:
  - jekyll-feed
  - jekyll-paginate
  - octopress-debugger
exclude:
  - Gemfile
  - Gemfile.lock

# Podcast Feed Settings

itunes-description:  Ben Etherington and Chris Radcliff have a lot of interests, and with a lot of interests come a lot of complaints. They started Notion.farm to convince each other the world isn't quite so bad.
subtitle: Start with a rant, end with a new idea.
lang: en-us
album-art: /images/NF-album-art-3000.jpg
copyright: Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International
keywords: haven't-built-this-list-yet
author: Chris Radcliff and Ben Etherington
explicit: 'no'
block-from-itunes: 'no'
